###

GET http://localhost:4000/index HTTP/1.1

###

POST http://localhost:4000/index 
Content-Type: application/json

{
    "id": "256",
    "name": "brunoedu",
    "ocupacion": "Monitor",
    "email": "brunoedu@gmail.com"
    
}

###

GET http://localhost:4000/index/6266d4c7130f3c9c4aa85fa4 HTTP/1.1

###

PUT http://localhost:4000/index/6266dcad358797860601f3dd 
Content-Type: application/json

{
    "name": "brunoeduupdated"
}

### 
DELETE http://localhost:4000/index/6266d84729d40a28f0037979