###

GET http://localhost:4000 HTTP/1.1

###

POST http://localhost:4000
Content-Type: application/json

{
    "id": "256",
    "name": "brunoedu",
    "ocupacion": "Monitor",
    "email": "brunoedu@gmail.com"
    
}

###

GET http://localhost:4000/ HTTP/1.1

###

PUT http://localhost:4000/
Content-Type: application/json

{
    "name": "brunoeduupdated"
}

### 
DELETE http://localhost:4000/626834c4ccbaa744862d2234