###

GET http://localhost:4000/Empleados

###

POST http://localhost:4000/Empleados
Content-Type: application/json

{
    "name": "brunoedu",
    "apellido": "postsiiiiiifunviona",
    "telefono": "465465446",
    "datanaixement": "22101999",
    "ocupacion": "Tecnico",
    "dni": "4543242",
    "email": "brunoedu22@gmail.com",
    "password": "Mati1234"
    
}


###

GET http://localhost:4000/ HTTP/1.1

###

PUT http://localhost:4000/
Content-Type: application/json

{
    "name": "brunoeduupdated"
}

### 
DELETE http://localhost:4000/626834c4ccbaa744862d2234